# Generated by Django 4.2.25 on 2025-10-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('activity_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='زمینه فعالیت')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='آخرین تاریخ خرید')),
                ('is_satisfied', models.BooleanField(blank=True, null=True, verbose_name='آیا از خرید راضی بوده؟')),
                ('customer_validation', models.CharField(blank=True, choices=[('good', 'خوب'), ('medium', 'متوسط'), ('bad', 'بد')], max_length=10, null=True, verbose_name='اعتبارسنجی مشتری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'گزارش تماس',
                'verbose_name_plural': 'گزارش\u200cهای تماس',
                'ordering': ['-last_purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شرکت')),
                ('ceo_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مدیرعامل')),
                ('ceo_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره مدیرعامل')),
                ('product_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع محصول')),
                ('port_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام بندر')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کشور')),
                ('loading_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='زمان بارگیری')),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع معامله')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت محصول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'اعلام بار شرکتی',
                'verbose_name_plural': 'اعلام بارهای شرکتی',
                'ordering': ['-loading_date'],
            },
        ),
        migrations.CreateModel(
            name='PrivateDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('product_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع محصول')),
                ('port_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام بندر')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کشور')),
                ('loading_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='زمان بارگیری')),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع معامله')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت محصول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'اعلام بار خصوصی',
                'verbose_name_plural': 'اعلام بارهای خصوصی',
                'ordering': ['-loading_date'],
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='related_customer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='related_opportunity',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
