# Generated by Django 4.2.25 on 2025-10-10 13:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_callreport_companydeclaration_privatedeclaration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Activity Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.fieldactivity', verbose_name='Parent Activity')),
            ],
            options={
                'verbose_name': 'Field Activity',
                'verbose_name_plural': 'Field Activities',
            },
        ),
        migrations.DeleteModel(
            name='CompanyDeclaration',
        ),
        migrations.DeleteModel(
            name='PrivateDeclaration',
        ),
        migrations.AlterModelOptions(
            name='callreport',
            options={'ordering': ['-number'], 'verbose_name': 'Call Report', 'verbose_name_plural': 'Call Reports'},
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='activity_field',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='customer_validation',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='is_satisfied',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='last_purchase_date',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='callreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callreport',
            name='last_purchase',
            field=models.DateField(blank=True, null=True, verbose_name='Last Purchase'),
        ),
        migrations.AddField(
            model_name='callreport',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='callreport',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='callreport',
            name='purchase_satisfaction',
            field=models.BooleanField(blank=True, default=False, verbose_name='Purchase Satisfaction'),
        ),
        migrations.AddField(
            model_name='callreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='callreport',
            name='validation',
            field=models.BooleanField(blank=True, default=False, verbose_name='Validation'),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='callreport',
            name='field_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='call_reports', to='crm.fieldactivity', verbose_name='Field of Activity'),
        ),
    ]
