# Generated by Django 4.2.25 on 2025-10-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_loadingtime_cargoannouncement_loading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoannouncement',
            name='sales_expert_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sales expert name'),
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Transaction Type')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.transactiontype', verbose_name='Transaction Type')),
            ],
            options={
                'verbose_name': 'Transaction Type Level',
                'verbose_name_plural': 'Transaction Type Levels',
            },
        ),
        migrations.AddField(
            model_name='cargoannouncement',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CargoAnnouncement', to='crm.transactiontype', verbose_name='Transaction Type'),
        ),
    ]
