# Generated by Django 4.2.25 on 2025-10-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_cargoannouncement_sales_expert_name_transactiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoannouncement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='cargoannouncement',
            name='product_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='product price'),
        ),
    ]
