# Generated by Django 4.2.25 on 2025-10-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_cargoannouncement_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_type', models.CharField(choices=[('market_place', 'MarketPlace'), ('market_outside', 'MarketOutside'), ('quota', 'Quota'), ('overhead', 'Overhead')], default='market_place', max_length=20, verbose_name='Purchase type')),
                ('market_place_type', models.CharField(blank=True, choices=[('agreement', 'Agreement'), ('cash', 'Cash')], max_length=20, null=True, verbose_name='MarketPlace Type')),
                ('yekta_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='yekta code')),
                ('market_outside_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='market outside address')),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='postal code')),
                ('market_outside_number', models.IntegerField(blank=True, null=True, verbose_name='market outside number')),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='buyer name')),
                ('overhead_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('overhead_number', models.IntegerField(blank=True, null=True, verbose_name='number')),
                ('agreement_kotazh', models.CharField(blank=True, max_length=100, null=True, verbose_name='Agreement kotazh')),
                ('cash_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='user')),
                ('cash_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='password')),
                ('cash_kotazh', models.CharField(blank=True, max_length=100, null=True, verbose_name='cash kotazh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_process', to='crm.callreport', verbose_name='Call Report')),
            ],
            options={
                'verbose_name': 'Purchase Process',
                'verbose_name_plural': 'Purchase Processes',
            },
        ),
    ]
