# Generated by Django 4.2.25 on 2025-10-15 10:52

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_purchaseprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseprocess',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='updated_at',
            field=django_jalali.db.models.jDateField(auto_now=True),
        ),
    ]
