# Generated by Django 4.2.25 on 2025-10-15 11:32

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_purchaseprocess_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseprocess',
            options={'ordering': ['-created_at'], 'verbose_name': 'Purchase Process', 'verbose_name_plural': 'Purchase Processes'},
        ),
        migrations.AddField(
            model_name='purchaseprocess',
            name='destination_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Destination Name'),
        ),
        migrations.AddField(
            model_name='purchaseprocess',
            name='quota_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quota Number'),
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='agreement_kotazh',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Agreement Kotazh'),
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Buyer Name'),
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='cash_kotazh',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cash Kotazh'),
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='cash_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cash Password'),
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='cash_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cash User'),
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='market_outside_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Market Outside Address'),
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='market_outside_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Market Outside Number'),
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='overhead_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Overhead Address'),
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='overhead_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Overhead Number'),
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Updated At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseprocess',
            name='yekta_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yekta Code'),
        ),
    ]
