# Generated by Django 4.2.25 on 2025-10-15 12:17

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_purchaseprocess_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('market_place', 'MarketPlace'), ('market_outside', 'MarketOutside'), ('quota', 'Quota')], max_length=20, verbose_name='Sale Type')),
                ('sale_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Sale Date')),
                ('purchase_process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_report', to='crm.purchaseprocess', verbose_name='Purchase Process')),
            ],
            options={
                'verbose_name': 'Sale Report',
                'verbose_name_plural': 'Sale Reports',
            },
        ),
    ]
