# Generated by Django 4.2.25 on 2025-10-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_salereport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salereport',
            options={'ordering': ['-sale_date'], 'verbose_name': 'Sale Report', 'verbose_name_plural': 'Sale Reports'},
        ),
        migrations.AlterField(
            model_name='salereport',
            name='sale_type',
            field=models.CharField(choices=[('market_place', 'MarketPlace'), ('market_outside', 'MarketOutside'), ('quota', 'Quota'), ('overhead', 'Overhead')], max_length=20, verbose_name='Sale Type'),
        ),
        migrations.CreateModel(
            name='SupplyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Supply Status')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.supplystatus', verbose_name='Parent Supply Status')),
            ],
            options={
                'verbose_name': 'Supply Status Level',
                'verbose_name_plural': 'Supply Status Levels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Name')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='Purchase Price')),
                ('selling_price', models.IntegerField(blank=True, null=True, verbose_name='Selling Price')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Profit')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Amount')),
                ('deposit', models.IntegerField(blank=True, null=True, verbose_name='Deposit')),
                ('account_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Account Remaining')),
                ('buyer', models.BooleanField(default=False, verbose_name='Buyer')),
                ('seller', models.BooleanField(default=False, verbose_name='Seller')),
                ('supplier', models.BooleanField(default=False, verbose_name='Supplier')),
                ('sales_expert_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sales Expert Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sale_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='crm.salereport', verbose_name='Sale Report')),
                ('supply_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.supplystatus', verbose_name='Quota Supply Status Level')),
            ],
            options={
                'verbose_name': 'Quota Sale',
                'verbose_name_plural': 'Quota Sales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Overhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Number')),
                ('sale_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overhead', to='crm.salereport', verbose_name='Sale Report')),
            ],
            options={
                'verbose_name': 'Overhead Sale',
                'verbose_name_plural': 'Overhead Sales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MarketPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Name')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight')),
                ('market_price', models.IntegerField(blank=True, null=True, verbose_name='Market Price')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='Purchase Price')),
                ('selling_price', models.IntegerField(blank=True, null=True, verbose_name='Selling Price')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Profit')),
                ('unofficial', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Unofficial')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Amount')),
                ('deposit', models.IntegerField(blank=True, null=True, verbose_name='Deposit')),
                ('account_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Account Remaining')),
                ('buyer', models.BooleanField(default=False, verbose_name='Buyer')),
                ('seller', models.BooleanField(default=False, verbose_name='Seller')),
                ('supplier', models.BooleanField(default=False, verbose_name='Supplier')),
                ('sales_expert_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sales Expert Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('weight_barname', models.IntegerField(blank=True, null=True, verbose_name='Weight Barname')),
                ('sale_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace', to='crm.salereport', verbose_name='Sale Report')),
                ('supply_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.supplystatus', verbose_name='MarketPlace Supply Status Level')),
            ],
            options={
                'verbose_name': 'MarketPlace Sale',
                'verbose_name_plural': 'MarketPlace Sales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MarketOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Name')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='Purchase Price')),
                ('selling_price', models.IntegerField(blank=True, null=True, verbose_name='Selling Price')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Profit')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Amount')),
                ('deposit', models.IntegerField(blank=True, null=True, verbose_name='Deposit')),
                ('account_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Account Remaining')),
                ('buyer', models.BooleanField(default=False, verbose_name='Buyer')),
                ('seller', models.BooleanField(default=False, verbose_name='Seller')),
                ('supplier', models.BooleanField(default=False, verbose_name='Supplier')),
                ('sales_expert_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sales Expert Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('weight_barname', models.IntegerField(blank=True, null=True, verbose_name='Weight Barname')),
                ('sale_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketoutside', to='crm.salereport', verbose_name='Sale Report')),
                ('supply_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.supplystatus', verbose_name='MarketOutside Supply Status Level')),
            ],
            options={
                'verbose_name': 'Market Outside Sale',
                'verbose_name_plural': 'Market Outside Sales',
                'ordering': ['-id'],
            },
        ),
    ]
