# Generated by Django 4.2.24 on 2025-09-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'کارشناس فروش'), (2, 'حسابدار'), (3, 'سوپر یوزر'), (4, 'مدیر فروش'), (5, 'سرپرست تیم'), (6, 'مدیر عامل')], default=1),
        ),
    ]
