# Generated by Django 4.2.25 on 2025-10-27 14:23

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_date',
            field=django_jalali.db.models.jDateField(auto_now=True, null=True),
        ),
    ]
