# Generated by Django 4.2.25 on 2025-11-08 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خبر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='تصویر خبر')),
                ('content', models.TextField(verbose_name='متن کامل خبر')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('tags', models.CharField(help_text='تگ\u200cها را با کاما جدا کنید', max_length=200, verbose_name='تگ\u200cها')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-published_date'],
            },
        ),
    ]
