# Generated by Django 4.2.25 on 2025-11-08 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
    ]
