# Generated by Django 4.2.25 on 2025-11-10 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_news_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLivestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('product_price', models.IntegerField(verbose_name='قیمت کالا')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا نهاد های دام',
            },
        ),
    ]
