# Generated by Django 4.2.25 on 2025-11-15 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_organicproducts_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFeedKhoshab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='Default/DefaultImg.png', null=True, upload_to='', verbose_name='عکس')),
                ('description', models.TextField(verbose_name='عنوان')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'خوراک دام خوشاب',
            },
        ),
        migrations.AlterField(
            model_name='organicproducts',
            name='product_photo',
            field=models.ImageField(blank=True, default='Default/DefaultImg.png', null=True, upload_to='', verbose_name='عکس کالا'),
        ),
        migrations.AlterField(
            model_name='purchaselivestock',
            name='product_photo',
            field=models.ImageField(blank=True, default='Default/DefaultImg.png', null=True, upload_to='', verbose_name='عکس کالا'),
        ),
    ]
