# Generated by Django 4.2.25 on 2025-11-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_purchaselivestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselivestock',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس کالا'),
        ),
    ]
