# Generated by Django 4.2.25 on 2025-11-15 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_animalfeedkhoshab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalfeedkhoshab',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
