# Generated by Django 4.2.25 on 2025-11-15 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_supplyinglivestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalRefinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='Default/DefaultImg.png', null=True, upload_to='', verbose_name='عکس')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='عنوان')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'پالیشگاه دام',
            },
        ),
    ]
