# Generated by Django 4.2.25 on 2025-11-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_plantrefinery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('number', models.IntegerField(verbose_name='شماره موبایل')),
                ('message', models.TextField(verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'تماس با ما',
            },
        ),
    ]
