# Generated by Django 4.2.25 on 2025-11-16 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='crate_deta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='زمان ارسال'),
            preserve_default=False,
        ),
    ]
