# Generated by Django 4.2.25 on 2025-11-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_contact_crate_deta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='crate_deta',
            field=models.DateField(auto_now_add=True, verbose_name='زمان ارسال'),
        ),
    ]
