# Generated by Django 4.2.25 on 2025-11-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_contact_crate_deta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=10, verbose_name='شماره موبایل'),
        ),
    ]
